### PR TITLE
Major rewrite

### LINKED ISSUE #31: Remove dependency on serde_bytes
Parse bytestrings of indefinite length [without using the ByteBuf wrapper](https://github.com/pyfisch/cbor/blob/e3bacca2a1765efe682926aed775e9bf65ce4715/src/de.rs#L123).

Also refactor parsing indefinite length UTF8-strings.

### LINKED ISSUE #32: Support zero copy deserialization

### LINKED ISSUE #37: Packed encoding for structs is broken when fields are conditionally skipped
Because serde doesn't provide field indices when serializing, the serializer currently guesses the index based off of the number of fields serialized. This doesn't work when fields are conditionally skipped, however:

```rust
extern crate serde;
extern crate serde_cbor;
#[macro_use]
extern crate serde_derive;

#[derive(Serialize, Deserialize)]
struct Foo {
    a: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    b: Option<u32>,
    c: u32,
}

#[test]
fn foo() {
    let foo = Foo {
        a: 0,
        b: None,
        c: 1,
    };
    let buf = serde_cbor::ser::to_vec_packed(&foo).unwrap();
    serde_cbor::from_slice::<Foo>(&buf).unwrap();
}
```

```
running 1 test
test foo ... FAILED

failures:

---- foo stdout ----
	thread 'foo' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `c`")', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    foo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

error: test failed, to rerun pass '--lib'

Completed with code 101
```

### PR DESCRIPTION
**Pull request by sfackler**
This commit consists of a rewrite of basically all of the serialization
and deserialization logic. The API and internals are based heavily off
of serde_json, in particular, the error type and support for borrowed
deserialization. The deserialization logic is now based off of the tag
byte lookup table described in appendix B of RFC 7049. It's a bit more
verbose, but compiles down to a jump table so there should be some
decent performance benefits in deserialization. It should also resolve
some longstanding correctness issues with deserialization of indefinite
length maps and sequences. The packed encoding can now properly handle
conditionally skipped fields and doesn't need special logic on the
deserialization side due to new serde features.

Closes #37
Closes #36
Closes #32
Closes #31

### CODE REVIEW

File: src/de.rs [hunk 1]
```diff
@@ -1,479 +1,960 @@
...
+                let len = self.parse_u64()?;
+                if len > usize::max_value() as u64 {
+                    return Err(self.error(ErrorCode::LengthOutOfRange));
+                }
+                self.parse_bytes(len as usize, visitor)
+            }
+            0x5c...0x5e => Err(self.error(ErrorCode::UnassignedCode)),
+            0x5f => self.parse_indefinite_bytes(visitor),
+
+            /// Major type 3: a text string
```
Comment (pyfisch) [inline src/de.rs]: Use normal comment.

File: src/de.rs [hunk 2]
```diff
@@ -1,479 +1,960 @@
...
-            _ => unreachable!(),
+    fn next(&mut self) -> Result<Option<u8>> {
+        self.read.next().map_err(Error::io)
+    }
+
+    fn peek(&mut self) -> Result<Option<u8>> {
+        self.read.peek().map_err(Error::io)
+    }
+
+    fn eat(&mut self) {
```
Comment (pyfisch) [inline src/de.rs]: Maybe `fn consume` like in `BufReader`?

File: src/error.rs [hunk 3]
```diff
@@ -1,92 +1,141 @@
...
-            Error::SizeError => "size error",
-            Error::Io(ref error) => StdError::description(error),
-            Error::FromUtf8(ref error) => error.description(),
-            Error::Custom(ref s) => s,
-            Error::StopCode => "unexpected stop code",
-            Error::TrailingBytes => "unexpected trailing bytes",
-            Error::__Nonexhaustive => unreachable!(),
+        match self.0.code {
+            ErrorCode::Io(ref err) => error::Error::description(err),
+            _ => "JSON error",
```
Comment (pyfisch) [inline src/error.rs]: "CBOR error"

**Comment by jq-rs** [comment]
Looks fantastic! Maybe 1.0 after these changes? If so, maybe we can get rid of unmaintained on the crate description after 1.0 as it really scares everybody?

**Comment by pyfisch** [comment]
> Maybe 1.0 after these changes?
Issue #3 is still open. I would like to see this fixed but it does not seem to be a priority for serde itself (and might even require a breaking release for the main serde crate). Before 1.0 the crate should also be fuzzed again and used for some time.

> If so, maybe we can get rid of unmaintained on the crate description after 1.0 as it really scares everybody?

If I can find a trustworthy person wanting to maintain the crate the unmaintained can be removed. dtolnay rejected the idea to move the crate to the @serde-rs organization so it can't probably become an official serde crate. Maybe @sfackler wants to adopt the crate but he did not say so yet. (If no one is found to adopt the crate we can discuss to make the unmaintained label smaller as most long-standing issues are resolved with this rewrite and I will still review issues and PRs)

**Comment by sfackler** [comment]
Yeah, I'd be happy to adopt the crate if that'd help with things!

The other big change that I'd want to make before a 1.0 is to overhaul Value to more fully support everything in CBOR. There are some tricks that the toml crate pulled with TOML datetime values that we can hopefully use here to get tags and things like that out in a useable way.

**Comment by sfackler** [comment]
Updated!

**Comment by pyfisch** [comment]
Thanks a lot!

**Comment by arthurprs** [comment]
This is great work.

I think the readme unmaintained alert will throw a lot of people off though, maye remode it?
