### PR TITLE
fixup ErrorCode::Io variant for feature unsealed_read_write

### LINKED ISSUE #134: Feature unsealed_read_write should work without std
Run `cargo build --no-default-features --features unsealed_read_write`.

It fails with:

```
error[E0599]: no variant or associated item named `Io` found for type `error::ErrorCode` in the current scope
   --> src/error.rs:53:30
    |
53  |             code: ErrorCode::Io,
    |                              ^^ variant or associated item not found in `error::ErrorCode`
...
263 | pub(crate) enum ErrorCode {
    | ------------------------- variant or associated item `Io` not found here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `serde_cbor`.

To learn more, run the command again with --verbose.
```

@baloo now we know why `Error::Io` is needed.

### PR DESCRIPTION
**Pull request by baloo**
Fixes #134
This partially reverts commit a8be10ec8aa7328c0a601cc6bed18149aca6b9c1.

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -267,6 +269,8 @@ pub(crate) enum ErrorCode {
     Message,
     #[cfg(feature = "std")]
     Io(io::Error),
+    #[cfg(all(not(feature = "std"), feature = "unsealed_read_write"))]
```
Comment (pyfisch) [inline src/error.rs]: I'd suggest to use `#[allow(unused)]` here instead.
(The reasoning is that writing these feature bounds correctly will quickly become too complex)

Comment (baloo) [reply src/error.rs]: sounds fair
